version: '3'
services:

  #Drupal Service
  webserver:
    build: ./nginx-php-drupal
    container_name: anpd
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "443:443"
    networks:
      - app-network
    volumes:
      - .volumes/modules:/var/www/drupal/web/modules
      - .volumes/profiles:/var/www/drupal/web/profiles
      - .volumes/themes:/var/www/drupal/web/themes
      # this takes advantage of the feature in Docker that a new anonymous
      # volume (which is what we're creating here) will be initialized with the
      # existing content of the image at the same location
      - .volumes/sites:/var/www/sites

  #MySQL Service
  db:
    build: ./mysql
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge


#Volumes
volumes:
  modules:
  profiles:
  themes:
  sites: