version: '3'
services:

  #Nginx Service
  webserver:
    build: ./nginx-php-drupal
    container_name: anpd
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
      - "443:443"
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql/mysql-server:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ASdf456+
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge