FROM alpine:latest


ENV TZ=Europe/Kiev
ENV PHP_V 7.3
# USER www-data
# runuser -l userNameHere -c 'command'
# runuser -l userNameHere -c '/path/to/command arg1 arg2'
ENV APKS \
    nginx \  
    #nginx/1.16.1
    supervisor \
    php-cli \
    php-fpm \
    php-common \
    php-mysqli \
    php-xml \
    php-xmlrpc \
    php-curl \
    php-gd \
    # imagick \
    php-cli \
    php-dev \
    php-imap \
    php-mbstring \
    php-opcache \
    php-soap \
    php-zip \
    php-intl \
    curl \
    wget \
    sudo \
    mc

ENV PHP_FPM_USER="www"
ENV PHP_FPM_GROUP="www"
ENV PHP_FPM_LISTEN_MODE="0660"
ENV PHP_MEMORY_LIMIT="512M"
ENV PHP_MAX_UPLOAD="50M"
ENV PHP_MAX_FILE_UPLOAD="200"
ENV PHP_MAX_POST="100M"
ENV PHP_DISPLAY_ERRORS="On"
ENV PHP_DISPLAY_STARTUP_ERRORS="On"
ENV PHP_ERROR_REPORTING="E_COMPILE_ERROR\|E_RECOVERABLE_ERROR\|E_ERROR\|E_CORE_ERROR"
ENV PHP_CGI_FIX_PATHINFO=0    

ADD https://dl.bintray.com/php-alpine/key/php-alpine.rsa.pub /etc/apk/keys/php-alpine.rsa.pub
RUN apk --update add ca-certificates
RUN echo "https://dl.bintray.com/php-alpine/v3.9/php-7.3" >> /etc/apk/repositories

RUN apk -U --no-cache add ${APKS} 

WORKDIR /workdir
COPY ./copy/ /files
RUN adduser -D -g 'www' www
RUN sed -i "s|;listen.owner\s*=\s*nobody|listen.owner = ${PHP_FPM_USER}|g" /etc/php7/php-fpm.d/www.conf
RUN sed -i "s|;listen.group\s*=\s*nobody|listen.group = ${PHP_FPM_GROUP}|g" /etc/php7/php-fpm.d/www.conf
RUN sed -i "s|;listen.mode\s*=\s*0660|listen.mode = ${PHP_FPM_LISTEN_MODE}|g" /etc/php7/php-fpm.d/www.conf
RUN sed -i "s|user\s*=\s*nobody|user = ${PHP_FPM_USER}|g" /etc/php7/php-fpm.d/www.conf
RUN sed -i "s|group\s*=\s*nobody|group = ${PHP_FPM_GROUP}|g" /etc/php7/php-fpm.d/www.conf
RUN sed -i "s|;log_level\s*=\s*notice|log_level = notice|g" /etc/php7/php-fpm.d/www.conf #uncommenting line 


RUN sed -i "s|display_errors\s*=\s*Off|display_errors = ${PHP_DISPLAY_ERRORS}|i" /etc/php7/php.ini
RUN sed -i "s|display_startup_errors\s*=\s*Off|display_startup_errors = ${PHP_DISPLAY_STARTUP_ERRORS}|i" /etc/php7/php.ini
RUN sed -i "s|error_reporting\s*=\s*E_ALL & ~E_DEPRECATED & ~E_STRICT|error_reporting = ${PHP_ERROR_REPORTING}|i" /etc/php7/php.ini
RUN sed -i "s|;*memory_limit =.*|memory_limit = ${PHP_MEMORY_LIMIT}|i" /etc/php7/php.ini
RUN sed -i "s|;*upload_max_filesize =.*|upload_max_filesize = ${PHP_MAX_UPLOAD}|i" /etc/php7/php.ini
RUN sed -i "s|;*max_file_uploads =.*|max_file_uploads = ${PHP_MAX_FILE_UPLOAD}|i" /etc/php7/php.ini
RUN sed -i "s|;*post_max_size =.*|post_max_size = ${PHP_MAX_POST}|i" /etc/php7/php.ini
RUN sed -i "s|;*cgi.fix_pathinfo=.*|cgi.fix_pathinfo= ${PHP_CGI_FIX_PATHINFO}|i" /etc/php7/php.ini

# RUN cp /files/www.conf /etc/php7/php-fpm.d/www.conf
# RUN cp /files/nginx.conf /etc/nginx/nginx.conf
# RUN chown -R nginx:nginx /var/log
RUN mkdir -p /run/nginx
RUN mkdir -p /etc/nginx/sites-available/
# RUN cp -R -f /files/default /etc/nginx/sites-available/default
RUN mkdir -p /var/www/html
RUN touch /var/www/html/index.html
RUN echo "suka!" > /var/www/html/index.html
RUN chmod +rwx /var/www/html/index.html
RUN cp /files/test.php /var/www/html/test.php
RUN sed -i 's/user = www/user = nginx/g' /etc/php7/php-fpm.d/www.conf
RUN sed -i 's/group = www/group = nginx/g' /etc/php7/php-fpm.d/www.conf
EXPOSE 80
# ENTRYPOINT ["/usr/bin/supervisord", "-c", "/supervisord.conf"]
# /usr/bin/supervisord -c /files/supervisord.conf